# Generated by Django 6.0.3 on 2026-04-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
    ]
