# Generated by Django 6.0.3 on 2026-05-25

from django.db import migrations
from topics.management.commands.load_autoimmune_article import (
    PILLAR,
    ARTICLE_CONTENT,
)


def create_autoimmune_article(apps, schema_editor):
    Pillar = apps.get_model('topics', 'Pillar')
    Article = apps.get_model('topics', 'Article')

    pillar, _ = Pillar.objects.get_or_create(
        slug=PILLAR['slug'],
        defaults={
            'name':        PILLAR['name'],
            'description': PILLAR['description'],
            'icon':        PILLAR['icon'],
            'color':       PILLAR['color'],
            'order':       PILLAR['order'],
        },
    )

    Article.objects.update_or_create(
        slug='leaky-gut-autoimmune-root-cause',
        defaults={
            'title': (
                'Why Your Immune System Attacks You: '
                'The Leaky Gut Root Cause of Autoimmune Disease'
            ),
            'summary': (
                'Dr. Zsófia Clemens has shown that autoimmune disease begins not in the '
                'immune system — but in the gut. When the wrong foods damage your gut wall, '
                'foreign proteins flood your bloodstream, trigger a mistaken immune attack on '
                'your own tissues, and spark a cascade of chronic inflammation.'
            ),
            'ai_summary': (
                'Autoimmune disease is not a broken immune system. It begins when certain foods '
                'damage the gut lining, proteins leak into the bloodstream, and the immune system '
                '— doing its job — mistakes your own tissues for invaders. Remove the gut-damaging '
                'foods, the barrier heals, the immune trigger disappears, and in many cases the '
                'disease reverses. Dr. Clemens\' clinic has confirmed gut permeability normalization '
                'within 3–4 weeks on the Paleolithic Ketogenic Diet, with complete remission in '
                'Crohn\'s, Type 1 diabetes, Hashimoto\'s, Graves\' disease, and rheumatoid arthritis.'
            ),
            'content':   ARTICLE_CONTENT,
            'pillar':    pillar,
            'order':     1,
            'published': True,
        },
    )


def reverse_autoimmune_article(apps, schema_editor):
    Article = apps.get_model('topics', 'Article')
    Article.objects.filter(slug='leaky-gut-autoimmune-root-cause').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_mindset_success_pillar_and_greene_article'),
    ]

    operations = [
        migrations.RunPython(
            create_autoimmune_article,
            reverse_autoimmune_article,
        ),
    ]
