# Generated by Django 6.0.3 on 2026-03-22 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_tag_remove_post_tag_post_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('rating', models.IntegerField(choices=[(1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5)),
                ('summary', models.TextField(max_length=300)),
                ('review_content', models.TextField()),
                ('buy_link', models.URLField(blank=True, help_text='Direct link to buy the book')),
                ('affiliate_link', models.URLField(blank=True, help_text='Your Amazon affiliate link')),
                ('recommended', models.BooleanField(default=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_reviews', to='blog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
