# Generated by Django 6.0.3 on 2026-03-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bookreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('reading', 'Currently Reading'), ('wishlist', 'Wish List')], default='read', max_length=20),
        ),
    ]
